name: http_study
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true