name: git_application
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # https://pub.dev/packages/http
  http: ^0.13.4
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.4.0
  # https://pub.dev/packages/webview_flutter
  webview_flutter:

dev_dependencies:
  #https://pub:dev/packages/freezed
  freezed:

  # https://pub.dev/packages/build_runner
  build_runner:

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true